#!/bin/sh
BASEDIR=$(dirname $0)
cd $BASEDIR/..

#
#   CI/CD script for AlthingiClient image.
#
#   How to run:
#
#   `client <commit-build-id>`
#
#   What is does:
#
#   1. Stops currently running container
#   2. Removes all exited containers
#   3. Deletes althingi-client images
#   4. Pulls the <commit-build-id> container
#   5. Runs the new version with --no-deps -d flags
#       Create a overwrite docker-compose file with the correct <commit-build-id>
#       Runs `up` on the two docker-compose.yaml files
#       Deletes the overwrite file (cleanup)
#

echo "Updating althing-client image to tag: $1";
echo "version: '3'\n\
services:\n\
    client:\n\
        image: einarvalur/althingi-client:$1\n\
" > docker-compose.client.$1.yaml

docker-compose stop client
docker rm $(docker ps -aq -f "status=exited")
docker rmi $(docker images -f "reference=einarvalur/althingi-client" -q)
docker pull einarvalur/althingi-client:$1
docker-compose -f docker-compose.yaml -f docker-compose.client.$1.yaml up --no-deps -d client

rm docker-compose.client.$1.yaml

echo "althing-client image up-to-date: $1";