#!/bin/sh
BASEDIR=$(dirname $0)
cd $BASEDIR/..

#
#   CI/CD script for AlthingiServer image.
#
#   How to run:
#
#   `server <commit-build-id>`
#
#   What is does:
#
#   1. Stops currently running container
#   2. Removes all exited containers
#   3. Deletes althingi-server images
#   4. Pulls the <commit-build-id> container
#   5. Runs the new version with --no-deps -d flags
#       Create a overwrite docker-compose file with the correct <commit-build-id>
#       Runs `up` on the two docker-compose.yaml files
#       Deletes the overwrite file (cleanup)
#

echo "Updating althing-server image to tag: $1";
echo "version: '3'\n\
services:\n\
    server:\n\
        image: einarvalur/althingi-server:$1\n\
" > docker-compose.server.$1.yaml

docker-compose stop server
docker rm $(docker ps -aq -f "status=exited")
docker rmi $(docker images -f "reference=einarvalur/althingi-server" -q)
docker pull einarvalur/althingi-server:$1
docker-compose -f docker-compose.yaml -f docker-compose.server.$1.yaml up --no-deps -d server

rm docker-compose.server.$1.yaml

echo "althing-server image up-to-date: $1";