#!/bin/sh
BASEDIR=$(dirname $0)
cd $BASEDIR/..

#
#   CI/CD script for AlthingiSource image.
#
#   How to run:
#
#   `source <commit-build-id>`
#
#   What is does:
#
#   1. Stops currently running container
#   2. Removes all exited containers
#   3. Deletes althingi-source images
#   4. Pulls the <commit-build-id> container
#   5. Runs the new version with --no-deps -d flags
#       Create a overwrite docker-compose file with the correct <commit-build-id>
#       Runs `up` on the two docker-compose.yaml files
#       Deletes the overwrite file (cleanup)
#

echo "Updating althing-source image to tag: $1";
echo "version: '3'\n\
services:\n\
    source:\n\
        image: einarvalur/althingi-source:$1\n\
" > docker-compose.source.$1.yaml

docker-compose stop source
docker rm $(docker ps -aq -f "status=exited")
docker rmi $(docker images -f "reference=einarvalur/althingi-source" -q)
docker pull einarvalur/althingi-source:$1
docker-compose -f docker-compose.yaml -f docker-compose.source.$1.yaml up --no-deps -d source

rm docker-compose.source.$1.yaml

echo "althing-source image up-to-date: $1";